### ISSUE TITLE
Requirements wrong / Instructions don't work on reportedly supported version of node

### ISSUE THREAD

**Issue by dagelf** [casejs/CASE#87]
```
coenraad@coenraad-u22:~$ npx create-case-app my-case-app

Creating new CASE app in /home/coenraad/my-case-app

✔ Successfully installed dependencies for my-case-app
✔ Successfully seeded default users for my-case-app

🎉 The "my-case-app" CASE app has been created successfully!



> start
> nodemon

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): entities/**/* app-config.ts
[nodemon] watching extensions: ts
[nodemon] starting `npm run compile`

> compile
> tsc && node node_modules/@casejs/case/server/src/main.js

error TS18003: No inputs were found in config file '/home/coenraad/my-case-app/tsconfig.json'. Specified 'include' paths were '["entities/**/*.ts","app-config.ts"]' and 'exclude' paths were '["dist"]'.


Found 1 error.

[nodemon] process failed, unhandled exit code (2)
[nodemon] 
[nodemon] Either the command has a syntax error,
[nodemon] or it is exiting with reserved code 2.
[nodemon] 
[nodemon] To keep nodemon running even after a code 2,
[nodemon] add this to the end of your command: || exit 1
[nodemon] 
[nodemon] Read more here: https://git.io/fNOAG
[nodemon] 
[nodemon] nodemon will stop now so that you can fix the command.
[nodemon] 
[nodemon] Error
    at Bus.<anonymous> (/home/coenraad/my-case-app/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:525:35)
    at ChildProcess.<anonymous> (/home/coenraad/my-case-app/node_modules/nodemon/lib/monitor/run.js:219:11)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
coenraad@coenraad-u22:~$ node -v
v18.15.0
coenraad@coenraad-u22:~$ npm -v
9.6.2
coenraad@coenraad-u22:~$ npx -v
9.6.2
coenraad@coenraad-u22:~$ cat /etc/issue
Ubuntu 22.04.2 LTS \n \l

coenraad@coenraad-u22:~
```

**Comment by dagelf** [comment]
Same with latest node:

```
coenraad@coenraad-u22:~$ node -v
v18.18.2
coenraad@coenraad-u22:~$ npm -v
9.8.1
coenraad@coenraad-u22:~$ 
```

**Comment by brunobuddy** [comment]
@dagelf thank you for this issue, I fixed the run script, it was a regression. you can create a new app running 
```
npx create-case-app my-case-app
```
